image: robertofilho/maven-java8:java8-awscli # java7 com maven
stages:
  - test
cache:
  paths:
    - .m2/
test:
  stage: test
  script:
    - mvn test -Dmaven.repo.local=/cache/.m2 # Cache maven repository
