image: robertofilho/maven-java8:java8-awscli # java7 com maven
stages:
  - test

variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository # Cache maven repository
  
test:
  stage: test
  script:
    - mvn test
